GraphicalPractice/Models/AccountModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Security;

namespace GraphicalPractice.Models
{
    public class UsersContext : DbContext
    {
        public UsersContext()
            : base("DefaultConnection")
        {
        }

        public DbSet<UserProfile> UserProfiles { get; set; }
    }

    [Table("UserProfile")]
    public class UserProfile
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        public string UserName { get; set; }
    }

    public class RegisterExternalLoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        public string ExternalLoginData { get; set; }
    }

    public class LocalPasswordModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ExternalLogin
    {
        public string Provider { get; set; }
        public string ProviderDisplayName { get; set; }
        public string ProviderUserId { get; set; }
    }
}

GraphicalPractice/Controllers/CirclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraphicalPractice.Controllers
{
    public class CirclesController : Controller
    {
        //
        // GET: /Circles/

        public ActionResult Index()
        {
            return View();
        }

    }
}

GraphicalPractice/Controllers/EnterExitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraphicalPractice.Controllers
{
    public class EnterExitController : Controller
    {
        //
        // GET: /EnterExit/
        public ActionResult Index()
        {
            return View();
        }

    }
}

GraphicalPractice/Controllers/FirstGraphController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraphicalPractice.Controllers
{
    public class FirstGraphController : Controller
    {
        //
        // GET: /FirstGraph/

        public ActionResult Index()
        {
            return View();
        }

    }
}

GraphicalPractice/Controllers/HistogramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraphicalPractice.Controllers
{
    public class HistogramController : Controller
    {
        //
        // GET: /Histogram/

        public ActionResult Index()
        {
            return View();
        }

    }
}

GraphicalPractice/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraphicalPractice.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "A place to learn about D3, Crossfilter, and Processing.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GraphicalPractice/Controllers/SimpleBarChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraphicalPractice.Controllers
{
    public class SimpleBarChartController : Controller
    {
        //
        // GET: /SimpleBarChart/

        public ActionResult Index()
        {
            return View();
        }

    }
}

GraphicalPractice/Controllers/SimpleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraphicalPractice.Controllers
{
    public class SimpleController : Controller
    {
        //
        // GET: /Simple/

        public ActionResult Index()
        {
            return View();
        }       
    }
}

GraphicalPractice/Controllers/TChartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraphicalPractice.Controllers
{
    public class TChartsController : Controller
    {
        //
        // GET: /TCharts/

        public ActionResult Index()
        {
            return View();
        }

    }
}

GraphicalPractice/Views/Circles/Index.cshtml
@{
    ViewBag.Title = "Three Little Circles";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Graphical Practice</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}
<style>
    svg {
        margin: 10px;
        border: solid 1px #7AC0DA;
    }
</style>
<h2>Three Little Circles</h2>
<script type="text/javascript">
    function randX() {
        return 20 + 650 * Math.random();
    };
    function randY() {
        return 20 + 300 * Math.random();
    };
    function randomLocation() {
        d3.selectAll("#svg circle")
            .transition()
            .attr("cy", randY)
            .attr("cx", randX)
    };
    function newCircle() {
        d3.selectAll("#svg circle")
                .data([40, 80, 150, 230, 420])
            .enter().append("circle")
                .attr("r", 12)
                .attr("cy", randY)
                .attr("cx", randX);
    };
    function databindRadius() {        
        d3.selectAll("#svg circle")
            .transition()
            .attr("r", Math.sqrt); //Computes sqrt(databound value) without an anon function
    };
    function resetRadius() {
        d3.selectAll("#svg circle")
            .transition()
            .attr("r", 12);
    };
</script>
<fieldset>    
    <a href="#" onclick="newCircle();">Add circles</a> | 
    <a href="#" onclick="randomLocation();">Random (x,y)</a> | 
    <a href="#" onclick="databindRadius();">Databind radius</a> | 
    <a href="#" onclick="resetRadius();">Reset radius</a>
</fieldset>
<svg id="svg" width="700px" height="350px">
    <circle cx="118.09953443706036" cy="45" r="12"></circle>
</svg>

GraphicalPractice/Views/EnterExit/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Graphical Practice</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}
<h2>Enter() and Exit()</h2>
<script type="text/javascript">
    function addParagraphs() {
        var p = d3.select("#content").selectAll("p")
            .data([4, 8, 15, 16, 23, 42])
            .text(function (d) { return "I’m number " + d + "!"; });

        p.enter().append("p")
            .text(function (d) { return "I’m number " + d + "!"; });
    };

    function removeParagraphs() {
        var p = d3.select('#content').selectAll("p")
            .data([4, 8])
            .text(function (d) { return "Updated " + d; });

        p.exit().remove();
    };
</script>
<fieldset>
     <a href="#" onclick="addParagraphs();">Add paragraphs</a>
    <a href="#" onclick="removeParagraphs();">Remove paragraphs</a>
</fieldset>

GraphicalPractice/Views/FirstGraph/Index.cshtml
@{
    ViewBag.Title = "First Graph (Object constancy)";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Graphical Practice</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}
<style>

@@import url(http://fonts.googleapis.com/css?family=PT+Serif|PT+Serif:b|PT+Serif:i|PT+Sans|PT+Sans:b);

    html {
      min-width: 1040px;
    }

    body {
      background: #fcfcfa;
      color: #333;
      font-family: "PT Serif", serif;
      margin: 1em auto 4em auto;
      position: relative;
      width: 960px;
    }

    header,
    footer,
    h1,
    h2,
    h3,
    h4,
    aside {
      color: #000;
      font-family: "PT Sans", sans-serif;
    }

    h1 {
      font-size: 64px;
      font-weight: 300;
      letter-spacing: -2px;
      margin: .3em 0 .1em 0;
    }

    h2 {
      margin-top: 2em;
    }

    h1, h2 {
      text-rendering: optimizeLegibility;
    }

    h2 a {
      color: #ccc;
      left: -20px;
      position: absolute;
      width: 740px;
    }

    footer {
      font-size: small;
      margin-top: 8em;
    }

    header aside {
      margin-top: 80px;
    }

    header aside,
    footer aside {
      color: #636363;
      text-align: right;
    }

    aside {
      font-size: small;
      right: 0;
      position: absolute;
      width: 180px;
    }

    .attribution {
      font-size: small;
      margin-bottom: 2em;
    }

    body > p, li > p {
      line-height: 1.5em;
    }

    body > p {
      width: 720px;
    }

    body > blockquote {
      width: 640px;
    }

    li {
      width: 680px;
    }

    a {
      color: steelblue;
    }

    a:not(:hover) {
      text-decoration: none;
    }

    pre, code, textarea {
      font-family: "Menlo", monospace;
    }

    code {
      line-height: 1em;
    }

    textarea {
      font-size: 100%;
    }

    body > pre {
      border-left: solid 2px #ccc;
      padding-left: 18px;
      margin: 2em 0 2em -20px;
    }

    .html .value,
    .javascript .string,
    .javascript .regexp {
      color: #756bb1;
    }

    .html .tag,
    .css .tag,
    .javascript .keyword {
      color: #3182bd;
    }

    .comment {
      color: #636363;
    }

    .html .doctype,
    .javascript .number {
      color: #31a354;
    }

    .html .attribute,
    .css .attribute,
    .javascript .class,
    .javascript .special {
      color: #e6550d;
    }

    svg {
      font: 10px sans-serif;
    }

    .axis path, .axis line {
      fill: none;
      stroke: #000;
      shape-rendering: crispEdges;
    }

    sup, sub {
      line-height: 0;
    }

    q:before,
    blockquote:before {
      content: "“";
    }

    q:after,
    blockquote:after {
      content: "”";
    }

    blockquote:before {
      position: absolute;
      left: 2em;
    }

    blockquote:after {
      position: absolute;
    }

    /*end general styles*/

    svg {
      font: 10px sans-serif;
      background-color: white;
    }

    .bar rect {
      fill: #8C9599;
    }

    .bar:hover rect {
      fill: #4C4237;
    }

    .value {
      fill: white;
    }

    .axis {
      shape-rendering: crispEdges;
    }

    .axis path {
      stroke: none;
    }

    .x.axis line {
      stroke: #fff;
      stroke-opacity: .8;
    }

    .x.axis text {
        fill: #8C9599;
    }

    .y.axis path {
      stroke: black;
    }

    #chart {
        margin: 10px;
    }

    text.label {
        fill: #8C9599;
    }
</style>
<h2>First Graph (Object constancy)</h2>
<p id="menu"><b>Top States by Age Bracket, 2008</b><br>Age: <select></select>
<p id="chart">

<aside>Source: <a href="http://www.census.gov/popest/archives/2000s/vintage_2008/" target="_blank">Census Bureau</a></aside>



<script type="text/javascript">
    var margin = { top: 20, right: 40, bottom: 10, left: 40 },
        width = 700,
        height = 250 - margin.top - margin.bottom;

    var format = d3.format(".1%"),
        states,
        age;

    var x = d3.scale.linear()
        .range([0, width]);

    var y = d3.scale.ordinal()
        .rangeRoundBands([0, height], .1);

    var xAxis = d3.svg.axis()
        .scale(x)
        
        .orient("top")
        //.tickSize(-height - margin.bottom)
        .tickSize(-11)
        .tickFormat(format);

    var svg = d3.select("#chart").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        //.style("margin-left", -margin.left + "px")
      .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    svg.append("g")
        .attr("class", "x axis");

    //svg.append("g")
    //    .attr("class", "y axis")
    //  .append("line")
    //    .attr("class", "domain")
    //    .attr("y2", height);

    var menu = d3.select("#menu select")
        .on("change", change);

    d3.csv("../states-age.csv.txt", function(data) {
        states = data;

        var ages = d3.keys(states[0]).filter(function (key) {
                return key != "State" && key != "Total";
        });

        states.forEach(function (state) {
                ages.forEach(function (age) {
                    state[age] = state[age] / state.Total;
                });
        });

        menu.selectAll("option")
                .data(ages)
              .enter().append("option")
                .text(function (d) { return d; });

        menu.property("value", "18 to 24 Years");

        redraw();
    });

    var altKey;

    d3.select(window)
        .on("keydown", function () { altKey = d3.event.altKey; })
        .on("keyup", function () { altKey = false; });

    function change() {
        clearTimeout(timeout);

        d3.transition()
            .duration(altKey ? 7500 : 750)
            .each(redraw);
    }

    function redraw() {
        var age1 = menu.property("value"),
            top = states.sort(function (a, b) { return b[age1] - a[age1]; }).slice(0, 10);

        y.domain(top.map(function (d) { return d.State; }));

        var bar = svg.selectAll(".bar")
            .data(top, function (d) { return d.State; });

        var barEnter = bar.enter().insert("g", ".axis")
            .attr("class", "bar")
            .attr("transform", function (d) { return "translate(0," + (y(d.State) + height) + ")"; })
            .style("fill-opacity", 0);

        barEnter.append("rect")
            .attr("width", age && function (d) { return x(d[age]); })
            .attr("height", y.rangeBand());

        barEnter.append("text")
            //.style("fill", "yellow")
            .attr("class", "label")
            .attr("x", -3)
            .attr("y", y.rangeBand() / 2)
            .attr("dy", ".35em")
            .attr("text-anchor", "end")
            .text(function (d) { return d.State; });

        barEnter.append("text")
            .attr("class", "value")
            .attr("x", age && function (d) { return x(d[age]) - 3; })
            .attr("y", y.rangeBand() / 2)
            .attr("dy", ".35em")
            .attr("text-anchor", "end");

        x.domain([0, top[0][age = age1]]);

        var barUpdate = d3.transition(bar)
            .attr("transform", function (d) { return "translate(0," + (d.y0 = y(d.State)) + ")"; })
            .style("fill-opacity", 1);

        barUpdate.select("rect")
            .attr("width", function (d) { return x(d[age]); });

        barUpdate.select(".value")
            .attr("x", function (d) { return x(d[age]) - 3; })
            .text(function (d) { return format(d[age]); });

        var barExit = d3.transition(bar.exit())
            .attr("transform", function (d) { return "translate(0," + (d.y0 + height) + ")"; })
            .style("fill-opacity", 0)
            .remove();

        barExit.select("rect")
            .attr("width", function (d) { return x(d[age]); });

        barExit.select(".value")
            .attr("x", function (d) { return x(d[age]) - 3; })
            .text(function (d) { return format(d[age]); });

        d3.transition(svg).select(".x.axis")
            .call(xAxis);
    }

    var timeout = setTimeout(function () {
        menu.property("value", "65 Years and Over").node().focus();
        change();
    }, 5000);

</script>

GraphicalPractice/Views/Histogram/Index.cshtml
@{
    ViewBag.Title = "Histogram";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Graphical Practice</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}
<style>
    svg {
        border: 1px solid black;
        background: white;
    }

    .axis .domain, .axis .tick {
        stroke: #000;
        fill: none;
    }

    .title {
        fill: #666;
        font-family: Helvetica, sans-serif; /* Helvetica is cool, right? */
        text-anchor: middle;
        font-size: 24px;
    }

    .bar {
        fill: #fcc;
        stroke: #444;
    }
</style>
<h2>Histogram</h2>
<div id='chart'></div>
<script type="text/javascript">
    var width = 640;
    var height = 480;
    var root = d3.select('#chart').append('svg')
        .attr({
            'width': width,
            'height': height,
        });

    // Render the title.
    var titleHeight = 50;
    root.append('text')
        .attr({
            'class': 'title',
            'x': width / 2,
            'y': titleHeight / 2,
        })
        .text('Skull-splitting power!');

    // Simulate 500 rolls of the axe.
    var rollDie = function (numSides) {
        return 1 + Math.floor(Math.random() * numSides);
    };

    var MAX_ROLL = 4 + 4 + 6 + 6;
    var rollHisto = d3.range(MAX_ROLL + 1).map(function () { return 0; });
    for (var i = 0; i < 500; i++) {
        var rolled = rollDie(4) + rollDie(4) + rollDie(6) + rollDie(6);
        rollHisto[rolled]++;
    }

    var yAxisWidth = 50;
    var xAxisHeight = 50;

    // Define the root g element.
    var histoWidth = width - yAxisWidth;
    var histoHeight = height - xAxisHeight - titleHeight;
    var histoG = root.append('g')
        .attr({
            'class': 'histo',
            'transform': 'translate(' + yAxisWidth + ', ' + titleHeight + ')',
        });


    // Render our axis.
    var xScale = d3.scale.linear()
        .domain([0, rollHisto.length])
        .range([0, histoWidth]);
    var yScale = d3.scale.linear()
        .domain([0, d3.max(rollHisto) * 1.2])
        .range([histoHeight, 0]);

    var xAxis = d3.svg.axis().scale(xScale);
    histoG.append('g')
        .attr({
            'class': 'x axis',
            'transform': 'translate(0, ' + histoHeight + ')',
        })
        .call(xAxis);

    var yAxis = d3.svg.axis().scale(yScale).orient('left');
    histoG.append('g')
        .attr('class', 'y axis')
        .call(yAxis);

    // Render the dice bars.
    histoG.selectAll('rect.bar')
        .data(rollHisto).enter()
      .append('rect')
        .attr({
            'class': 'bar',
            'x': function (d, i) { return xScale(i - 0.5); },
            'width': xScale(1) - xScale(0),
            'y': yScale,
            'height': function (d) { return yScale(0) - yScale(d); },
        });
</script>

GraphicalPractice/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

GraphicalPractice/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

GraphicalPractice/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Graphical Practice</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem nulla, ultrices ac vestibulum quis, feugiat eget nibh. Mauris pellentesque pellentesque felis, nec rutrum massa iaculis ac. Duis viverra dignissim lacus, eu mollis nulla porta vehicula. 
            </p>
        </div>
    </section>
}
<h3>D3 Examples</h3>
<ol class="round">
    <li class="one">
        @Html.ActionLink("Simple examples", "Index", "Simple")
    </li>
    <li class="one">
        @Html.ActionLink("Enter() and Exit()", "Index", "EnterExit")
    </li>
    <li class="one">
        @Html.ActionLink("Three Little Circles", "Index", "Circles")
    </li>
    <li class="one">
        @Html.ActionLink("First Graph (Object constancy)", "Index", "FirstGraph")
    </li>
    <li class="one">
        @Html.ActionLink("Simple Bar Chart", "Index", "SimpleBarChart")
    </li>
    <li class="one">
        @Html.ActionLink("Histogram", "Index", "Histogram")
    </li>
     <li class="one">
        @Html.ActionLink("TCharts Prototype", "Index", "TCharts")
    </li>
</ol>

GraphicalPractice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />        
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")        
        @Scripts.Render("~/bundles/jquery")
        <script src="http://d3js.org/d3.v3.min.js"></script>                        
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><!-- @Html.ActionLink("your logo here", "Index", "Home") --> </p>
                </div>
                <div class="float-right">
                    <section id="login" />
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>                            
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section id="content" class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>        
        @RenderSection("scripts", required: false)
    </body>
</html>

GraphicalPractice/Views/SimpleBarChart/Index.cshtml
@{
    ViewBag.Title = "Simple Bar Chart";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Graphical Practice</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}
<style>
    #chart {
        width: 500px;
        height: 100px;
    }
    #chart div {
        background-color: steelblue;
        font: 10px sans-serif;
        text-align: right;
        padding: 3px;
        margin: 1px;
        color: white;
    }
</style>
<h2>Simple Bar Chart</h2>
<div id="chart" class="chart" />
<script type="text/javascript">
    var data = [4, 8, 15, 16, 23, 42];
    //var chart = d3.select("section#content").append("div")
    //    .attr("class", "chart");
    var chart = d3.select("#chart");

    var xScale = d3.scale.linear()
        .domain([0, d3.max(data)])
        .range(["0px", chart.style("width")]);
    var yScale = d3.scale.ordinal()
        .domain(data).rangeBands();

    chart.selectAll("div")
        .data(data)
    .enter().append("div")
        .style("width", xScale)
        .text(function (d) { return d; });
</script>